name: Frontend AWS S3 Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Packages
        run: npm install
        working-directory: ./frontend

      - name: Build production build
        run: npm run build
        working-directory: ./frontend

      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./build s3://gitranker --delete
        working-directory: ./frontend